jdbcUrl: "jdbc:mysql://127.0.0.1:3306/petrus_study_plus?characterEncoding=utf-8"
jdbcUsername: "root"
jdbcPwd: "password"
author: "xiezongnan"

# 是否启用lombok 影响entity;dto;vo
withLombok: true
# 默认使用的数据库
globalSchema: "petrus_study_plus"
# 默认的包路径
globalBasePackage: "com.xiezongnan.api"
#globalEntityPackage:
#globalEntityClassPrefix:
globalEntityClassSuffix: "Entity"
#globalServicePackage:
#globalServiceClassPrefix:
#globalServiceClassSuffix:
#globalServiceImplPackage:
#globalServiceImplClassPrefix:
#globalServiceImplClassSuffix:
#globalMapperPackage:
#globalMapperClassPrefix:
#globalMapperClassSuffix:
# Xml文件的相对路径 project/module/src/main/resources/{globalXmlPath} 可以使用 /xxx/xxx 或者 xxx/xxx 或者 xxx.xxx 风格
globalXmlPath: "mapper.gen"
#globalXmlFilePrefix:
#globalXmlFileSuffix:
#globalControllerPackage:
#globalControllerClassPrefix:
#globalControllerClassSuffix:
#globalDtoPackage:
#globalDtoClassPrefix:
globalDtoClassSuffix: "Dto"
#globalMapstructPackage:
#globalMapstructClassPrefix:
globalMapstructClassSuffix: "Converter"
#globalTableDefPackage:
#globalTableDefClassPrefix:
#globalTableDefClassSuffix:
#globalVoPackage:
#globalVoClassPrefix:
globalVoClassSuffix: "Vo"
# 默认生成至子项目的名称
globalSourceModuleName: "manual"
#sourceEntityModuleName:
#sourceDtoModuleName:
#sourceVoModuleName:
#sourceMapstructModuleName:
#sourceMapperModuleName:
#sourceTableDefModuleName:
#sourceXmlModuleName:
#sourceServiceModuleName:
#sourceServiceImplModuleName:
#sourceControllerModuleName:

### Tables Config Example
tables:
  - tableName: "tb_account"
#    schema:
    needGenerateEntity: true
    needGenerateDto: true
    needGenerateVo: true
    needGenerateMapper: true
    needGenerateXml: true
    needGenerateService: true
    needGenerateMapstruct: true
    needGenerateController: true
    needGenerateTableDef: true
#    author:
#    basePackage:
#    entityPackage:
#    dtoPackage:
#    voPackage:
#    servicePackage:
#    serviceImplPackage:
#    mapperPackage:
#    xmlPath:
#    controllerPackage:
#    mapstructPackage:
#    tableDefPackage: