spring:
  datasource:
    url: jdbc:mysql://localhost:3306/petrus_study_plus
    username: root
    password: password

knife4j:
  enable: true
  openapi:
    title: Knife4j-PetrusStudyPlus
    description: "PetrusStudyPlus"
    email: xiezongnan@foxmail.com
    concat: 谢宗南
    url:
    version: v4.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
